In [ ]:
import numpy as np

## Universal Array Commands/Methods

- `.sqrt()`
- `.sum()`
- `.mean()`
- `.max()` `.min()`
- `.argmax()` `.argmin()`

---
1. `.sqrt()`

In [ ]:
# 1. sqrt()

# √25 --> 5  (5x5 = 25)
# √16 --> 4  (4x4 = 16)
# √9  --> 3  (3x3 = 9)
# √4  --> 2  (2x2 = 4)

arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Broadcasting - blast a single value/logic across a larger set of values
arr1 = arr1 * arr1

# np.sqrt() is a BROADING FUNCTION (because it broad the logic of √ to the array)

# It is going to broadcasting the logic of (√) into all the elements of [ 1  4  9 16 25 36 49 64 81]

print(arr1)

[ 1  4  9 16 25 36 49 64 81]


In [ ]:
print(np.sqrt(arr1))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


2. `.sum()`

In [ ]:
arr2 = np.random.randint(0,10,8)
print(arr2)

[4 7 4 0 5 9 9 9]


In [ ]:
print(arr2.sum()) # .sum() is NOT a broadcasting function

47


In [ ]:
# normal python of summing

list1 = [0,6,1,4,5,8,7,0]

#how can we sum this array?

# first loop through the array, then sum it

total = 0  # intialise a storage to 0

for x in list1:
  total = total + x

# 1st loop --> x = 0 , total = 0 --> total = total + x --> total = 0 + 0 --> total = 0
# 2nd loop --> x = 6 , total = 0 --> total = total + x --> total = 0 + 6 --> total = 6
# 3rd loop --> x = 1 , total = 6 --> total = total + x --> total = 6 + 1 --> total = 7
# 4th loop --> x = 4 , total = 7 --> total = total + x --> total = 7 + 4 --> total = 11
# 5th loop --> x = 5 , total = 11 --> total = total + x --> total = 11 + 5 --> total = 16
# 6th loop --> x = 8 , total = 16 --> total = total + x --> total = 16 + 8 --> total = 24
# 7th loop --> x = 7 , total = 24 --> total = total + x --> total = 24 + 7 --> total = 31
# 8th loop --> x = 0 , total = 31 --> total = total + x --> total = 31 + 0 --> total = 31

print(total)


31


3. `.mean()`

In [ ]:
arr3 = np.random.randint(0,10,5)
print(arr3)

[8 0 4 8 0]


In [ ]:
print(arr3.mean())# .mean() is NOT a broadcasting function

4.0


In [ ]:
# normal python of finding mean


list1 = [8,0,4,8,0]

total = 0

for x in list1:
  total = total + x

print(total/len(list1))

4.0


4. `.max()` `min()`

In [ ]:
arr4 = np.random.randint(0,100,5)
print(arr4)

[82 99 90 44 52]


In [ ]:
print(arr4.max())#It return the maximum value from the array

99


In [ ]:
print(arr4.min())#It will return the minimum value from the array

44


In [ ]:
# normal python of finding largest number in a list

list1 = [53,87,60,78,57]

#how can we find the largest number of this array?

largest = list1[0] # assume the first item is the largest (53) BEFORE LOOPING

for x in list1:
  if x > largest:
    largest = x

# 1st loop --> x = 53, largest =53 , (x > largest)? --> (53 > 53) ? --> FALSE --> u skip the if/else body
# 2nd loop --> x = 53, largest =53 , (x > largest)? --> (87 > 53) ? --> TRUE --> run if/else body --> largest = x --> largest = 87
# 3rd loop --> x = 60, largest =87 , (x > largest)? --> (60 > 87) ? --> FALSE --> u skip the if/else body
# 4th loop --> x = 78, largest =87 , (x > largest)? --> (78 > 87) ? --> FALSE --> u skip the if/else body
# 5th loop --> x = 57, largest =87 , (x > largest)? --> (57 > 87) ? --> FALSE --> u skip the if/else body

# END OF LOOP - LARGEST = 87


print(largest)

5. `.argmax()` `argmin()`



In [ ]:
arr5 = np.random.randint(0,50,5)
print(arr5)

[33 22  8 28 21]


In [ ]:
print(arr5.argmax())# .argmax() & .argmin() are NOT broadcasting functions

# gives u the postion/index of the maximum number in an array

0


In [ ]:
# normal python of finding the index of the largest number

list1 = [46,35,2,33,41]

largest = list1[0]

indexOfLargest = 0

for x in range(1,len(list1)):
  if list1[x] > largest:
    largest = list1[x]
    indexOfLargest = x

print(indexOfLargest)

# I am not going to explain how i did this

# I want you guys (students) to write down the flow-map and figure out (break down concepts urself using flooping flow)
# HOMEWORK/ TASK (1 WEEK)
# I expect a full explanation using comments

0


## 2D Array Axis Logic (rows and columns)

While working with 2-d arrays, we have to consider rows and columns.

In array terms (in data analysis):
- axis 0  --> vertical axis   --> columns
- axis 1  --> horizontal axis --> rows

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Sum all the vertical axis
print(arr_2d.sum(axis = 0))

# for example:

# sum each row's first number:
# 1 + 5 +  9 --> 15

# sum each row's second number:
# 2 + 6 +  10 --> 18

# sum each row's third number:
# 3 + 7 +  11 --> 21

# sum each row's four number:
# 4 + 8 +  12 --> 21

[15 18 21 24]


In [ ]:
# sum the horizontal axis
print(arr_2d.sum(axis = 1))

[10 26 42]


In [ ]:
print(arr_2d.shape)

# 3 rows, 4 columns (ROW IS ALWAYS FIRST)

(3, 4)


## Python's `round()` vs Numpy's `np.round()`

To conclude the difference on  numpy’s `np.round()` and python’s `round()`:

In [ ]:
#If you have an individual number we use --> round(),np.round()
#If you have an array of numbers we use --> np.round()

In [ ]:
num = 5.55555

print(round(num,2))
print(np.round(num,2))

5.56
5.56


#### Example 2 (Array Like Data Type)

`round()` is meant for rounding individual numbers and `does not support arrays or lists directly`.

In [ ]:
list1 = [12.4354645, 32.6554, 43.755]

round(list1,2)

TypeError: type list doesn't define __round__ method

In [ ]:
np.round(list1,2)# works since np.round() is a BROADCASTING FUNCTION

array([12.44, 32.66, 43.76])