In [ ]:
import numpy as np
import pandas as pd

arr1 = np.arange(10,41,10)
print(arr1)
print(type(arr1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
ser1 = pd.Series(arr1)
print(ser1)
print(type(ser1))


0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
#Pandas DataFrame

#Pandas series looks like below
list2d = [[10,20,30],
          [40,50,60],
          [70,80,90]]
ser1 = pd.Series(list2d)
print(ser1)

0    [10, 20, 30]
1    [40, 50, 60]
2    [70, 80, 90]
dtype: object


In [ ]:
#to make it into DataFrame

df=pd.DataFrame(list2d)
df #no need to write print, you can but it comes in matrix form

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
myindex = ['CA','NY','AZ']
mycolumn = ['Jan','Feb','Mar']
df1 = pd.DataFrame(data=list2d,index=myindex,columns=mycolumn)
df1

Jan  Feb  Mar
CA   10   20   30
NY   40   50   60
AZ   70   80   90

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, CA to AZ
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     3 non-null      int64
 1   Feb     3 non-null      int64
 2   Mar     3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes


In [ ]:
#Exercise

list1 = np.random.randint(1,100,12)
print(list1)

arr_2d = list1.reshape(4,3)
print(arr_2d)

myindex = ['Math','English','Coding','Science']
mycolumn = ['Yuen Shen','Ridanya','Chrysander']
df2 = pd.DataFrame(data=arr_2d,index=myindex,columns=mycolumn)
df2


[80 23 63 75 50 44 22  3 77 21 28 76]
[[80 23 63]
 [75 50 44]
 [22  3 77]
 [21 28 76]]


Yuen Shen  Ridanya  Chrysander
Math            80       23          63
English         75       50          44
Coding          22        3          77
Science         21       28          76

In [ ]:
#Reading csv. file
import numpy as np
import pandas as pd
df3 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/tips.csv')
df3

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011810e+15    Sun4458  
3      Nathaniel Harris  4.676140e+15    Sun5260  
4          Tonya Carter  4.832730e+15    Sun2251  
..                  ...           ...        ...  
239       Michael Avila  5.296070e+15    Sat2657  
240      Monica Sanders  3.506810e+15    Sat1766  
241          Keith Wong  6.011890e+15    Sat3880  
242        Dennis Dixon  4.375220e+12      Sat17  
243     Michelle Hardin  3.511450e+15    Thur672  

[244 rows x 11 columns]

# New Section

In [ ]:
print(type(df3))
df3.info()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    float64
 10  Payment ID        244 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 21.1+ KB


In [ ]:
print(df3.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')


In [ ]:
print(len(df3.columns))

11


In [ ]:
print(df3.index)

RangeIndex(start=0, stop=244, step=1)


In [ ]:
print(len(df3.index))

244


In [ ]:
#how to see certain element of dataframe

df3.head(7) #df3.head(), by default it will only shows top 5 rows

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251  
5          Erik Smith  2.131400e+14    Sun9679  
6  Kristopher Johnson  2.223730e+15    Sun5985

In [ ]:
df3.sample(10) #shows random data in the dataset

total_bill   tip     sex smoker   day    time  size  price_per_person  \
74        14.73  2.20  Female     No   Sat  Dinner     2              7.36   
204       20.53  4.00    Male    Yes  Thur   Lunch     4              5.13   
23        39.42  7.58    Male     No   Sat  Dinner     4              9.86   
138       16.00  2.00    Male    Yes  Thur   Lunch     2              8.00   
97        12.03  1.50    Male    Yes   Fri  Dinner     2              6.02   
53         9.94  1.56    Male     No   Sun  Dinner     2              4.97   
161       12.66  2.50    Male     No   Sun  Dinner     2              6.33   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
84        15.98  2.03    Male     No  Thur   Lunch     2              7.99   
196       10.34  2.00    Male    Yes  Thur   Lunch     2              5.17   

          Payer Name     CC Number Payment ID  
74     Ashley Harris  5.018290e+11    Sat6548  
204        Scott Kim  3.570610e+15   Thur2160  
23    Lance Peterson  3.542580e+15     Sat239  
138    Jason Burgess  3.561460e+15   Thur2710  
97      Eric Herrera  5.801160e+11    Fri9268  
53     Curtis Morgan  4.628630e+15    Sun4561  
161  Brandon Oconnor  4.406880e+15    Sun5879  
239    Michael Avila  5.296070e+15    Sat2657  
84       Jason Jones  4.442980e+15   Thur1944  
196      Eric Martin  3.044250e+13   Thur9862

In [ ]:
df3.tail(10) #shows last 10 rows

total_bill   tip     sex smoker   day    time  size  price_per_person  \
234       15.53  3.00    Male    Yes   Sat  Dinner     2              7.76   
235       10.07  1.25    Male     No   Sat  Dinner     2              5.04   
236       12.60  1.00    Male    Yes   Sat  Dinner     2              6.30   
237       32.83  1.17    Male    Yes   Sat  Dinner     2             16.42   
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name     CC Number Payment ID  
234    Tracy Douglas  4.097940e+15    Sat7220  
235    Sean Gonzalez  3.534020e+15    Sat4615  
236    Matthew Myers  3.543680e+15    Sat5032  
237     Thomas Brown  4.284720e+15    Sat2929  
238   Kimberly Crane  6.761840e+11    Sat9777  
239    Michael Avila  5.296070e+15    Sat2657  
240   Monica Sanders  3.506810e+15    Sat1766  
241       Keith Wong  6.011890e+15    Sat3880  
242     Dennis Dixon  4.375220e+12      Sat17  
243  Michelle Hardin  3.511450e+15    Thur672

In [ ]:
df3.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563495e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040732e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525320e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596450e+15

DataFrame Column Operations


In [ ]:

#we can access 1 column or multiple columns
#add new columns
#update and delete columns

df3['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df3[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
df3['tip_percentage'] = df3['tip']/df3['total_bill']*100
df3.head()
df3['tip_percentage'] = np.round(df3['tip_percentage'],2)
df3.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959            5.94  
1      Douglas Tucker  4.478070e+15    Sun4608           16.05  
2      Travis Walters  6.011810e+15    Sun4458           16.66  
3    Nathaniel Harris  4.676140e+15    Sun5260           13.98  
4        Tonya Carter  4.832730e+15    Sun2251           14.68

In [ ]:
# axis 0 >> row
# axis 1 >> column

df3.drop('tip_percentage',axis=1)
df3.drop('time',axis=1)

total_bill   tip     sex smoker   day  size  price_per_person  \
0         16.99  1.01  Female     No   Sun     2              8.49   
1         10.34  1.66    Male     No   Sun     3              3.45   
2         21.01  3.50    Male     No   Sun     3              7.00   
3         23.68  3.31    Male     No   Sun     2             11.84   
4         24.59  3.61  Female     No   Sun     4              6.15   
..          ...   ...     ...    ...   ...   ...               ...   
239       29.03  5.92    Male     No   Sat     3              9.68   
240       27.18  2.00  Female    Yes   Sat     2             13.59   
241       22.67  2.00    Male    Yes   Sat     2             11.34   
242       17.82  1.75    Male     No   Sat     2              8.91   
243       18.78  3.00  Female     No  Thur     2              9.39   

             Payer Name     CC Number Payment ID  tip_percentage  
0    Christy Cunningham  3.560330e+15    Sun2959            5.94  
1        Douglas Tucker  4.478070e+15    Sun4608           16.05  
2        Travis Walters  6.011810e+15    Sun4458           16.66  
3      Nathaniel Harris  4.676140e+15    Sun5260           13.98  
4          Tonya Carter  4.832730e+15    Sun2251           14.68  
..                  ...           ...        ...             ...  
239       Michael Avila  5.296070e+15    Sat2657           20.39  
240      Monica Sanders  3.506810e+15    Sat1766            7.36  
241          Keith Wong  6.011890e+15    Sat3880            8.82  
242        Dennis Dixon  4.375220e+12      Sat17            9.82  
243     Michelle Hardin  3.511450e+15    Thur672           15.97  

[244 rows x 11 columns]

DataFrame Index

In [ ]:
df3.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959            5.94  
1      Douglas Tucker  4.478070e+15    Sun4608           16.05  
2      Travis Walters  6.011810e+15    Sun4458           16.66  
3    Nathaniel Harris  4.676140e+15    Sun5260           13.98  
4        Tonya Carter  4.832730e+15    Sun2251           14.68

In [ ]:
df3.set_index('Payment ID').head(10) # to make definite change when choosing column as index
df3.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959            5.94  
1      Douglas Tucker  4.478070e+15    Sun4608           16.05  
2      Travis Walters  6.011810e+15    Sun4458           16.66  
3    Nathaniel Harris  4.676140e+15    Sun5260           13.98  
4        Tonya Carter  4.832730e+15    Sun2251           14.68

In [ ]:
df = df3.set_index('Payment ID')
df.head() #df here is to define only


total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name     CC Number  tip_percentage  
Payment ID                                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15            5.94  
Sun4608                 3.45      Douglas Tucker  4.478070e+15           16.05  
Sun4458                 7.00      Travis Walters  6.011810e+15           16.66  
Sun5260                11.84    Nathaniel Harris  4.676140e+15           13.98  
Sun2251                 6.15        Tonya Carter  4.832730e+15           14.68

In [ ]:
df = df.reset_index()
df.head()

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   
4    Sun2251       24.59  3.61  Female     No  Sun  Dinner     4   

   price_per_person          Payer Name     CC Number  tip_percentage  
0              8.49  Christy Cunningham  3.560330e+15            5.94  
1              3.45      Douglas Tucker  4.478070e+15           16.05  
2              7.00      Travis Walters  6.011810e+15           16.66  
3             11.84    Nathaniel Harris  4.676140e+15           13.98  
4              6.15        Tonya Carter  4.832730e+15           14.68

In [ ]:
df = df3.set_index('Payment ID')
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name     CC Number  tip_percentage  
Payment ID                                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15            5.94  
Sun4608                 3.45      Douglas Tucker  4.478070e+15           16.05  
Sun4458                 7.00      Travis Walters  6.011810e+15           16.66  
Sun5260                11.84    Nathaniel Harris  4.676140e+15           13.98  
Sun2251                 6.15        Tonya Carter  4.832730e+15           14.68

DataFrame Row Operations

In [ ]:
# access a single row
df.head()

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   
4    Sun2251       24.59  3.61  Female     No  Sun  Dinner     4   

   price_per_person          Payer Name     CC Number  tip_percentage  
0              8.49  Christy Cunningham  3.560330e+15            5.94  
1              3.45      Douglas Tucker  4.478070e+15           16.05  
2              7.00      Travis Walters  6.011810e+15           16.66  
3             11.84    Nathaniel Harris  4.676140e+15           13.98  
4              6.15        Tonya Carter  4.832730e+15           14.68

In [ ]:
# integer-based indexing
print(df.iloc[0]) # iloc means integer based, loc means based on string

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
tip_percentage                    5.94
Name: Sun2959, dtype: object


In [ ]:
print(df.iloc[1])

total_bill                       10.34
tip                               1.66
sex                               Male
smoker                              No
day                                Sun
time                            Dinner
size                                 3
price_per_person                  3.45
Payer Name              Douglas Tucker
CC Number           4478070000000000.0
tip_percentage                   16.05
Name: Sun4608, dtype: object


In [ ]:
# name-based indexing
print(df.loc['Sun2959'])

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
tip_percentage                    5.94
Name: Sun2959, dtype: object


In [ ]:
# slicing

df.iloc[1:6]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   

            price_per_person        Payer Name     CC Number  tip_percentage  
Payment ID                                                                    
Sun4608                 3.45    Douglas Tucker  4.478070e+15           16.05  
Sun4458                 7.00    Travis Walters  6.011810e+15           16.66  
Sun5260                11.84  Nathaniel Harris  4.676140e+15           13.98  
Sun2251                 6.15      Tonya Carter  4.832730e+15           14.68  
Sun9679                 6.32        Erik Smith  2.131400e+14           18.62

In [ ]:
df.iloc[[5,6,9,2]]

total_bill   tip   sex smoker  day    time  size  \
Payment ID                                                     
Sun9679          25.29  4.71  Male     No  Sun  Dinner     4   
Sun5985           8.77  2.00  Male     No  Sun  Dinner     2   
Sun3775          14.78  3.23  Male     No  Sun  Dinner     2   
Sun4458          21.01  3.50  Male     No  Sun  Dinner     3   

            price_per_person          Payer Name     CC Number  tip_percentage  
Payment ID                                                                      
Sun9679                 6.32          Erik Smith  2.131400e+14           18.62  
Sun5985                 4.38  Kristopher Johnson  2.223730e+15           22.81  
Sun3775                 7.39       Jerome Abbott  3.532120e+15           21.85  
Sun4458                 7.00      Travis Walters  6.011810e+15           16.66

In [ ]:
df.loc[['Sun2959','Sun5260']]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name     CC Number  tip_percentage  
Payment ID                                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15            5.94  
Sun5260                11.84    Nathaniel Harris  4.676140e+15           13.98

In [ ]:
# dropping rows
df.drop('Sun2959',axis=0).head(10)

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   
Sun5985           8.77  2.00    Male     No  Sun  Dinner     2   
Sun8157          26.88  3.12    Male     No  Sun  Dinner     4   
Sun6820          15.04  1.96    Male     No  Sun  Dinner     2   
Sun3775          14.78  3.23    Male     No  Sun  Dinner     2   
Sun2546          10.27  1.71    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name     CC Number  tip_percentage  
Payment ID                                                                      
Sun4608                 3.45      Douglas Tucker  4.478070e+15           16.05  
Sun4458                 7.00      Travis Walters  6.011810e+15           16.66  
Sun5260                11.84    Nathaniel Harris  4.676140e+15           13.98  
Sun2251                 6.15        Tonya Carter  4.832730e+15           14.68  
Sun9679                 6.32          Erik Smith  2.131400e+14           18.62  
Sun5985                 4.38  Kristopher Johnson  2.223730e+15           22.81  
Sun8157                 6.72         Robert Buck  3.514790e+15           11.61  
Sun6820                 7.52     Joseph Mcdonald  3.522870e+15           13.03  
Sun3775                 7.39       Jerome Abbott  3.532120e+15           21.85  
Sun2546                 5.14       William Riley  5.662880e+11           16.65

In [ ]:
dict1 = {
    'total_bill': 10.99,
    'tip': 1.50,
    'sex':'Female',
    'smoker':'No',
    'day':'Tue',
    'time':'Dinner',
    'size':4,
    'price_per_person':2.75,
    'Payer Name':'Jun',
    'CC Number': 2020202012
}


In [ ]:
ser1 = pd.Series(dict1)
df = pd.concat([df, ser1.to_frame().T], ignore_index=True)
df.tail()


total_bill   tip     sex smoker   day    time size price_per_person  \
242      17.82  1.75    Male     No   Sat  Dinner    2             8.91   
243      18.78   3.0  Female     No  Thur  Dinner    2             9.39   
244      10.99   1.5  Female     No   Tue  Dinner    4             2.75   
245      10.99   1.5  Female     No   Tue  Dinner    4             2.75   
246      10.99   1.5  Female     No   Tue  Dinner    4             2.75   

          Payer Name           CC Number  tip_percentage  
242     Dennis Dixon     4375220000000.0            9.82  
243  Michelle Hardin  3511450000000000.0           15.97  
244              Jun          2020202012             NaN  
245              Jun          2020202012             NaN  
246              Jun          2020202012             NaN

Pandas DataFrame 18 Oct 2025


In [ ]:
import numpy as np
import pandas as pd

arr1 = np.arange(10,41,10)
print(arr1)

[10 20 30 40]


In [ ]:
ser1 =pd.Series(arr1)
print(ser1)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
list_2d = [['10','20',30],
           [40,50,60],
           [70,80,90]]
ser1 = pd.Series(list_2d)
print(ser1)

0    [10, 20, 30]
1    [40, 50, 60]
2    [70, 80, 90]
dtype: object


In [ ]:
df = pd.DataFrame(list_2d)
df

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
myindex = ['CA','NY','AZ']
mycolumns = ['Jan','Feb','Mar']
df = pd.DataFrame(data = list_2d, index = myindex, columns = mycolumns)
df           #to print dataframe, no need to write print

Jan Feb  Mar
CA  10  20   30
NY  40  50   60
AZ  70  80   90

In [ ]:
list1 = np.random.randint(1,100,12)
print(list1)

arr_2d = list1.reshape(4,3)
print(arr_2d)

myindex = ['Math','English','Coding','Science']
mycolumns = ['Yuen Shen','Ridanya','Chrysander']
df = pd.DataFrame(data = arr_2d, index = myindex, columns = mycolumns)
df

[15 49 98 10 46 47 98 44  4 94 60 30]
[[15 49 98]
 [10 46 47]
 [98 44  4]
 [94 60 30]]


Yuen Shen  Ridanya  Chrysander
Math            15       49          98
English         10       46          47
Coding          98       44           4
Science         94       60          30

Reading CSV files


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tips (1) (1).csv")
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011810e+15    Sun4458  
3      Nathaniel Harris  4.676140e+15    Sun5260  
4          Tonya Carter  4.832730e+15    Sun2251  
..                  ...           ...        ...  
239       Michael Avila  5.296070e+15    Sat2657  
240      Monica Sanders  3.506810e+15    Sat1766  
241          Keith Wong  6.011890e+15    Sat3880  
242        Dennis Dixon  4.375220e+12      Sat17  
243     Michelle Hardin  3.511450e+15    Thur672  

[244 rows x 11 columns]

Conditional Filtering


In [ ]:
arr1 = np.array([102,121,232,2,12,32])
print(arr1 > 100)

[ True  True  True False False False]


In [ ]:
print(arr1[arr1 > 100])

[102 121 232]


In [ ]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251

In [ ]:
df['total_bill'] > 30  # shows only boolean results

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[df['total_bill'] > 30 ]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82   
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86   
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42   
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60   
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10   
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70   
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50   
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34   
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69   
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92   
175       32.90   3.11    Male    Yes   Sun  Dinner     2             16.45   
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32   
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
207       38.73   3.00    Male    Yes   Sat  Dinner     4              9.68   
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54   
237       32.83   1.17    Male    Yes   Sat  Dinner     2             16.42   
238       35.83   4.67  Female     No   Sat  Dinner     3             11.94   

                Payer Name     CC Number Payment ID  
11            Diane Macias  4.577820e+15    Sun6686  
23          Lance Peterson  3.542580e+15     Sat239  
39       Mr. Brandon Berry  6.011530e+15    Sat6373  
44             Todd Cooper  5.038470e+11    Sun2274  
47            James Barnes  3.552000e+15    Sun9677  
52            Emily Daniel  4.291280e+15    Sun6165  
56   James Christensen DDS  3.497940e+14    Sat8903  
59             Brian Ortiz  6.596450e+15    Sat8139  
83           Daniel Murphy  5.356180e+15   Thur8801  
85             Shawna Cook  6.011790e+15   Thur7972  
95           Aaron Bentley  1.800270e+14    Fri9628  
102          Heather Cohen  3.797710e+14    Sat6240  
112             Jeff Lopez  3.572870e+15     Sun591  
141         Steven Carlson  3.526520e+15   Thur1025  
142           Eric Andrews  4.356530e+15   Thur3621  
156          Ryan Gonzales  3.523150e+15    Sun7518  
167         Michael Lawson  3.566290e+15    Sun3719  
170          Gregory Clark  5.473850e+15    Sat1954  
173            Scott Perez  3.577120e+15    Sun9335  
175        Nathan Reynolds  3.703070e+14    Sun5109  
179           Brian Bailey  3.466560e+14    Sun9851  
180       James Hebert DDS  6.761690e+11    Sun7544  
182           Jose Parsons  4.112210e+15    Sun2337  
184            Stephen Cox  3.547800e+15    Sun5140  
187          David Barrett  4.792880e+15    Sun

In [ ]:
MoreThanThirty = df[df['total_bill'] > 30 ]
len(MoreThanThirty)

32

In [ ]:
female = df[df['sex'] == 'Female']
female

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
11        35.26  5.00  Female     No   Sun  Dinner     4              8.82   
14        14.83  3.02  Female     No   Sun  Dinner     2              7.42   
16        10.33  1.67  Female     No   Sun  Dinner     3              3.44   
..          ...   ...     ...    ...   ...     ...   ...               ...   
226       10.09  2.00  Female    Yes   Fri   Lunch     2              5.04   
229       22.12  2.88  Female    Yes   Sat  Dinner     2             11.06   
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
4          Tonya Carter  4.832730e+15    Sun2251  
11         Diane Macias  4.577820e+15    Sun6686  
14        Vanessa Jones  3.001670e+13    Sun3848  
16     Elizabeth Foster  4.240030e+15    Sun9715  
..                  ...           ...        ...  
226          Ruth Weiss  5.268690e+15    Fri6359  
229    Jennifer Russell  4.793000e+12    Sat3943  
238      Kimberly Crane  6.761840e+11    Sat9777  
240      Monica Sanders  3.506810e+15    Sat1766  
243     Michelle Hardin  3.511450e+15    Thur672  

[87 rows x 11 columns]

In [ ]:
print(True and False)

False


In [ ]:
print(True and True)

True


In [ ]:
print(True or False)

True


In [ ]:
df[(df['total_bill']>= 20) & (df['total_bill']<= 30)]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5         25.29  4.71    Male     No  Sun  Dinner     4              6.32   
7         26.88  3.12    Male     No  Sun  Dinner     4              6.72   
..          ...   ...     ...    ...  ...     ...   ...               ...   
229       22.12  2.88  Female    Yes  Sat  Dinner     2             11.06   
230       24.01  2.00    Male    Yes  Sat  Dinner     4              6.00   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   

           Payer Name     CC Number Payment ID  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251  
5          Erik Smith  2.131400e+14    Sun9679  
7         Robert Buck  3.514790e+15    Sun8157  
..                ...           ...        ...  
229  Jennifer Russell  4.793000e+12    Sat3943  
230   Michael Osborne  4.258680e+12    Sat7872  
239     Michael Avila  5.296070e+15    Sat2657  
240    Monica Sanders  3.506810e+15    Sat1766  
241        Keith Wong  6.011890e+15    Sat3880  

[65 rows x 11 columns]

In [ ]:
# I want to only get back the rows where size > 5 and its a Thursday
df[(df['size']> 5) & (df['day']=="Thur")]

total_bill  tip     sex smoker   day   time  size  price_per_person  \
125       29.80  4.2  Female     No  Thur  Lunch     6              4.97   
141       34.30  6.7    Male     No  Thur  Lunch     6              5.72   
143       27.05  5.0  Female     No  Thur  Lunch     6              4.51   

         Payer Name     CC Number Payment ID  
125  Angela Sanchez  5.038570e+11   Thur3948  
141  Steven Carlson  3.526520e+15   Thur1025  
143    Regina Jones  4.311050e+12   Thur6179

In [ ]:
# I want to only get back the rows where size > 5 and it is ANY OTHER DAY OTHER THAN THURSDAY
df[(df['size']> 5) & (df['day']!="Thur")]



total_bill  tip   sex smoker  day    time  size  price_per_person  \
156       48.17  5.0  Male     No  Sun  Dinner     6              8.03   

        Payer Name     CC Number Payment ID  
156  Ryan Gonzales  3.523150e+15    Sun7518

In [ ]:
# I want to only get back the rows where tips is less than 2 and female
df[(df['tip'] < 2) & (df['sex'] == 'Female')]

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
16        10.33  1.67  Female     No   Sun  Dinner     3              3.44   
57        26.41  1.50  Female     No   Sat  Dinner     2             13.20   
67         3.07  1.00  Female    Yes   Sat  Dinner     1              3.07   
82        10.07  1.83  Female     No  Thur   Lunch     1             10.07   
92         5.75  1.00  Female    Yes   Fri  Dinner     2              2.88   
111        7.25  1.00  Female     No   Sat  Dinner     1              7.25   
117       10.65  1.50  Female     No  Thur   Lunch     2              5.32   
118       12.43  1.80  Female     No  Thur   Lunch     2              6.22   
121       13.42  1.68  Female     No  Thur   Lunch     2              6.71   
132       11.17  1.50  Female     No  Thur   Lunch     2              5.58   
135        8.51  1.25  Female     No  Thur   Lunch     2              4.26   
145        8.35  1.50  Female     No  Thur   Lunch     2              4.18   
146       18.64  1.36  Female     No  Thur   Lunch     3              6.21   
147       11.87  1.63  Female     No  Thur   Lunch     2              5.94   
168       10.59  1.61  Female    Yes   Sat  Dinner     2              5.30   
215       12.90  1.10  Female    Yes   Sat  Dinner     2              6.45   

              Payer Name     CC Number Payment ID  
0     Christy Cunningham  3.560330e+15    Sun2959  
16      Elizabeth Foster  4.240030e+15    Sun9715  
57          Melody Simon  4.745390e+15    Sat8980  
67         Tiffany Brock  4.359490e+15    Sat3455  
82           Julie Moody  6.304130e+11   Thur4909  
92          Leah Ramirez  3.508910e+15    Fri3780  
111          Terri Jones  3.559220e+15    Sat4801  
117          Linda Zhang  3.560510e+15   Thur9593  
118  Dr. Caroline Tucker  5.020470e+11   Thur8084  
121         Laura Garcia  5.181480e+15   Thur2158  
132      Taylor Gonzalez  6.011990e+15   Thur7783  
135       Rebecca Harris  4.320270e+15   Thur6600  
145            Amy Young  4.285450e+12   Thur9331  
146        Kelly Estrada  6.046330e+10   Thur3941  
147   Annette Cunningham  6.759380e+11   Thur4780  
168         Sara Jimenez  5.020530e+11    Sat9795  
215         Jessica Owen  4.726900e+12    Sat6983

In [ ]:
# I want the rows that are weekends ONLY
df[(df['day']=="Sat") | (df['day']=="Sun")]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011810e+15    Sun4458  
3      Nathaniel Harris  4.676140e+15    Sun5260  
4          Tonya Carter  4.832730e+15    Sun2251  
..                  ...           ...        ...  
238      Kimberly Crane  6.761840e+11    Sat9777  
239       Michael Avila  5.296070e+15    Sat2657  
240      Monica Sanders  3.506810e+15    Sat1766  
241          Keith Wong  6.011890e+15    Sat3880  
242        Dennis Dixon  4.375220e+12      Sat17  

[163 rows x 11 columns]

In [ ]:
# i want the rows that are weekends ONLY and total_bill which is above the average


In [ ]:
np.average = df['total_bill'].mean()
df[(df['day']=="Sat") | (df['day']=="Sun") & (df['total_bill'] > np.average)]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5         25.29  4.71    Male     No  Sun  Dinner     4              6.32   
7         26.88  3.12    Male     No  Sun  Dinner     4              6.72   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

           Payer Name     CC Number Payment ID  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251  
5          Erik Smith  2.131400e+14    Sun9679  
7         Robert Buck  3.514790e+15    Sun8157  
..                ...           ...        ...  
238    Kimberly Crane  6.761840e+11    Sat9777  
239     Michael Avila  5.296070e+15    Sat2657  
240    Monica Sanders  3.506810e+15    Sat1766  
241        Keith Wong  6.011890e+15    Sat3880  
242      Dennis Dixon  4.375220e+12      Sat17  

[124 rows x 11 columns]