We are going to discuss how to ` select elements or groups of elements` from an array.

array = list

In [ ]:
import numpy as np

In [ ]:
#Creating a sample array

#.rand() --> create random number [0-1)


arr1 = np.random.rand(8)
print(arr1)

[0.05789523 0.99077868 0.36321523 0.01658582 0.37022838 0.19274561
 0.66663919 0.48117608]


## Bracket Indexing and *Selection*

In [ ]:
arr1[0] # indexing - accessing 1 item of the array

# indexing in numpy array is the same as indexing in normal python list

np.float64(0.05789523469606073)

In [ ]:
arr1[-1]

np.float64(0.481176077209136)

In [ ]:
arr1[2]

np.float64(0.36321523287471047)

In [ ]:
# slicing - accessing more than 1 item in the array
print(arr1[1:4])

[0.99077868 0.36321523 0.01658582]


# 2d array Indexing

`Indexing - getting 1 item of the array`

*   1D List - Rows of items
*   2D List - Columns & Rows of items

In [ ]:
#normal python list

# 1st number - row
# 2nd number - column

list_1d = [1,2,3,4,5,6,7,8,9]
list_2d = [[1,2,3],[4,5,6],[7,8,9]]

print(list_2d[1])
 # row 2 , column 2 --> row index 1, column index 1
print(list_2d[1][1])

[4, 5, 6]
5


In [ ]:
#LAST ROW FROM THE 2D LIST
print(list_2d[-1])

[7, 8, 9]


In [ ]:
#LAST ELEMENT FROM THE 2D LIST
print(list_2d[-1][-1])

9


In [ ]:
list_2d = [[10,20,30],[40,50,60],[70,80,90]] #normal python 2d list

#convert/typecast list --> array
arr_2d = np.array(list_2d)

print(arr_2d) # 2d numpy array

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# in numpy array, in order to index/slice, u can use the [ , ] notion INSTEAD OF [][]

# 2. [ , ] notation

print(arr_2d[0])
#row 1, column 1
print(arr_2d[1,1])
#row 2, last column
print(arr_2d[2,-1])
print(arr_2d[2,1])

[10 20 30]
50
90
80


In [ ]:
# in normal python 2d list, you cant use the [ , ] notation, only [][] notation
print(list_2d[1,1])

TypeError: list indices must be integers or slices, not tuple

# 2d array Slicing

`slicing - getting more than 1 item in the array`

*   1D List - Rows of items
*   2D List - Columns & Rows of items

In [ ]:
list_2d = [[10,20,30],[40,50,60],[70,80,90]] #normal python 2d list

#convert/typecast list --> array
arr_2d = np.array(list_2d)

print(arr_2d) # 2d numpy array

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
print(arr_2d[1:3])
print('---')
print(arr_2d[1:]) #shortcut

[[40 50 60]
 [70 80 90]]
---
[[40 50 60]
 [70 80 90]]


In [ ]:
print(arr_2d[1:3,1:3])
print('---')
print(arr_2d[1:,1:]) # shortcut

[[50 60]
 [80 90]]
---
[[50 60]
 [80 90]]


In [ ]:
print(arr_2d[:,-1]) # all rows, last column
print('---')
print(arr_2d[:,-1].reshape(3,1))

[30 60 90]
---
[[30]
 [60]
 [90]]


---
#### More Examples

<img src="https://i.ibb.co/jzPNtbq/Whats-App-Image-2024-06-16-at-20-44-41-cd8e9add.jpg" alt="Whats-App-Image-2024-06-16-at-20-44-41-cd8e9add" border="0" width="180">

In [ ]:
# array = np.array([np.arange(i, i + 6) for i in range(0, 60, 10)])

import numpy as np
list1 =[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]]
array = np.array(list1)

print(array)
print(array[0,3:5])
print(array[:,-4].reshape(6,1))
print(array[2,0])
print(array[2,2])
print(array[2,4])
print(array[4,0])
print(array[4,2])
print(array[4,4])
print(array[2::2,0::2])
print(array[4:,4:])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[3 4]
[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]
20
22
24
40
42
44
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]
