## Broadcasting

Broadcasting - `blast a single value/logic across a larger set of values`

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([333,444,555,666,777,888,999])

print(arr1)

[333 444 555 666 777 888 999]


In [ ]:
print(arr1[2:5])

[555 666 777]


In [ ]:
arr1[2:5] = 1
# do you think the above code will be this --> [333,444,1,888,999]

# It is going to broadcasting the value of (1) into all the elements of [2:5] --> 555,666,777

print(arr1)

[333 444   1   1   1 888 999]


---
#### Explanation
<div style="overflow: hidden; padding-top:15px;">
     <img src="https://i.ibb.co/tPmdkL8/Numpy-Broadcasting-p1.jpg" alt="Image Description" width="450" style="float: left;">
</div>

---

In [ ]:
# another exampe
arr2 = np.arange(0,8)
print(arr2)

[0 1 2 3 4 5 6 7]


In [ ]:
arr2[2:4] = 99

print(arr2)

[ 0  1 99 99  4  5  6  7]


In [ ]:
# YOU CANT DO THIS IN NORMAL PYTHON (THE CONCEPT OF BROADCASTING)

list1 = [0,1,2,3,4,5,6,7]

list1[2:4] =99
print(list1)

TypeError: must assign iterable to extended slice

In [ ]:
# another example
arr3 = np.arange(3,13)
print(arr3)

[ 3  4  5  6  7  8  9 10 11 12]


In [ ]:
print(arr3 + 3)

# do you think the above code will be this --> [ 3  4  5  6  7  8  9 10 11 12 3] ???
# ANSWER - NO


# It is going to broadcasting the logic of (+3) into all the elements of [ 3  4  5  6  7  8  9 10 11 12]

# Broadcasting - blast a single value/logic across a larger set of values

[ 6  7  8  9 10 11 12 13 14 15]


---
#### Explanation
<div style="overflow: hidden; padding-top:15px;">
     <img src="https://i.ibb.co/8KtMx9Z/Whats-App-Image-2024-02-23-at-13-28-20-04b8c3ad.jpg" alt="Image Description" width="450" style="float: left;">
</div>

---

## Conditional Selection

In [ ]:
#comparison operators

num1 = 5

print(num1>6)# boolean (true & false)

False


In [ ]:
# in comparison operators, broadcasting concept is included!

#Broadcasting - blast a single value/ logic across a larger set of values

arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr1 > 6 )

# it doesnt give u  [7  8  9 10]  --> like a lot of people think

# this is the result because first of all --> broadcastinG DOES NOT CHANGE THE LENGTH OF ARRAY
# second of all --> when you are comparing, it either gives u true or false  -->  Broadcasting - blast a single value across a larger set of values

#  [ 1  2  3  4  5  6  7  8  9 10] --> 10 numbers --> checking the logic 10 times

# it is going to BROADCAST the logic of (arr1 > 6) 10 times

[False False False False False False  True  True  True  True]


In [ ]:
# in order to do conditional filtering, wrap it inside the variable

print(arr1[arr1>6])

# arr1[condition] -->  arr1[arr1 > 6]

# arr1   [[False False False False False False  True  True  True  True]]
# arr1 -->  1     2     3     4     5     6     7      8     9    10

# so it filters the numbers that are TRUE and return it (nothing to do with broadcasting)
# basically return the ones that are true --> 7,8,9,10

[ 7  8  9 10]


In [ ]:
# another example (multiple condtions)

arr2 = np.arange(1,10)
print(arr2)

print('----')

# we want to get back the numbers that are between 4-8
#Tip : when you are looking into a range value , you need to use and condition why because both the numbers need to meet the logic requirements to return as true.
# Multiple condition , we use and/or

# single condition --> variable[variable condition statement]
# multiple conditions -> variable[(condition1)&(condition 2)]

print(arr2[(arr2 > 4) & (arr2 < 8)])# "&" --> "and"
print(arr2[(arr2 > 4) | (arr2 < 8)])# "|" --> "or" #Or condition

[1 2 3 4 5 6 7 8 9]
----
[5 6 7]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# another example

# generating 10 random numbers from 0-100
arr3 = np.random.randint(0,100,10)
print(arr3)
print('-------')
#filter in only the even numbers

print(arr3[arr3%2 == 0])

[42 37 45 57 83 84 41 87 18 45]
-------
[42 84 18]


# conditional filtering works with 2d arrays too

In [ ]:
arr_2d = np.random.randint(1,100,9).reshape(3,3)
print(arr_2d)
np.random.seed(100)
print('------')
print(arr_2d[arr_2d>50].reshape(5,1))


[[ 9 25 68]
 [88 80 49]
 [11 95 53]]
------
[[68]
 [88]
 [80]
 [95]
 [53]]
