In [ ]:
#Data Types
#8 Data types
#Logic
#if else
#for loop
#function

#Numpy

In [ ]:
# Data science is all about "using past data to predict (not telling) the future"

# YouTube – using past data (watch history) to predict (what appears on your homepage).
# ChatGPT – using past data (www from 2000 to 2024) to predict (responses to your prompts).
# Self-Driving Cars – using past data to predict (road paths and driving decisions).

# 2 parts of Data Science
# (i) Data analysis & visualisation
# (ii) Machine Learning & AI

# Part 1 of data science - Data analysis

# Data analysis - anlysing past data (formatting, cleaning data from excel sheet, text file, online... BEFORE machine learning)
# In data analysis, you will deal with 2 main PYTHON LIBRARIES - numpy & pandas

In [ ]:
# numpy - python library (extension, package)
# numpy is NOT PART OF THE "vanilla/base" python, it is an extension
# basically, "numpy" library is created with python code

# A programming library is just some pre-written code that you can use to make a programmer's life easier
# Libraries are often used to reduce the amount of code a programmer needs to write by providing reusable functions or classes that can be called upon as needed.

# Numpy - a library about python list (but with extra functionalities) - "more powerful list"

In [ ]:
# LIMITATION OF NORMAL PYTHON LIST

# add , remove, update, check length

  # we can solve this with Numpy arrays

# array = list

In [ ]:
#  "import" keyword --> use a third part library (for exampl, numpy)
#  "as"  keyword    --> "alias", shorten the variable name from "numpy" to "np" (industry standard)

import numpy as np

## 1.1 There are a few main ways to create `numpy arrays`

1. `array()`
2. `arange()`
3. `zeros and ones`
4. `linspace()`

# 1. array()

In [ ]:
list1 = [1,22,333] # normal python list
print(list1)
print(type(list1))

[1, 22, 333]
<class 'list'>


In [ ]:
# convert/typecast python list --> numpy array


array1 = np.array(list1)

print(array1)

print(type(array1))

[  1  22 333]
<class 'numpy.ndarray'>


# 2. arange()

In [ ]:
# 2 inputs --> start, stop (excluding stop)

# [0,10)

array2 = np.arange(0,10)

print(array2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
list1 = []# creating an empty list

for x in range(0,10):# range(0,10) - 0 1 2 3 4 5 6 8 9 --> 10 numbers --> 10 loops
  list1.append(x)

# "x" is a changing variable depending on which loop it is in

# 1st loop --> x = 0 --> list1.append(x) --> list1.append(0)  --> [0]
# 2nd loop --> x = 1 --> list1.append(x) --> list1.append(1)  --> [0,1]
# 3rd loop --> x = 2 --> list1.append(x) --> list1.append(2)  --> [0,1,2]

print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 2 inputs --> start, stop (excluding stop)
# 1 input  --> stop (excluding stop), DEFAULTS START TO 0

# if you ONLY provide 1 input in the .arange(), the starting number will DEFAULT to 0

array3 = np.arange(21)

print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 3 inputs --> start, stop (excluding stop), step
# 2 inputs --> start, stop (excluding stop)
# 1 input  --> stop (excluding stop), DEFAULTS START TO 0

# step size = increment/decrement amount

#--------------------------------------------------
# example of increment (increasing by x)

array4 = np.arange(0,21,2)

print(array4)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# creating the same output in NORMAL PYTHON (BEHIND THE SCENES OF NUMPY .arange())

list2 = []#Empty list

for x in range(0,21,2):
  list2.append(x)

print(list2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
# example of decrement (decreasing by x)

array5 = np.arange(21,5,-2)

print(array5)

[21 19 17 15 13 11  9  7]


In [ ]:
# common mistake

array6 = np.arange(21,5,2)
# I am starting from 21, ending at 5, by increasing 2 every time?????

print(array6) # empty array --> THERE IS NO SUCH THING

[]


# 3. zeros and ones

In [ ]:
array7=np.zeros(8)

print(array7)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array8 = np.ones(12)
print(array8)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# create a matrix of zeros & ones

# matrix (mathematical term) - rows & columns


array9 = np.zeros((4,7))#Creating a matrix of zeros with 4 rows and 7 columns


print(array9)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 4. linspace = linear(evenly) spacing

In [ ]:

# I want 21 EVENLY SPACED OUT NUMBERS from 0 to 5
# if you count, there are 21 numbers (21 numbers which are evenly spaced out = increment is the same)
#np.linspace(input1,input2,input3)
#input : Start Range
#Output : Stop Range
#How many numbers to return

array10 = np.linspace(0,5,21)

print(array10)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [ ]:
# another example

# I want 15 EVENLY SPACED OUT NUMBERS from 5 to 20

arr11 = np.linspace(5,20, 15)

print(arr11)
print("---"*10)
print(len(arr11))

[ 5.          6.07142857  7.14285714  8.21428571  9.28571429 10.35714286
 11.42857143 12.5        13.57142857 14.64285714 15.71428571 16.78571429
 17.85714286 18.92857143 20.        ]
------------------------------
15


## 1.2 Random numbers in numpy arrays

There are different ways to generate random numbers in a numpy array

1. `rand()`
2. `randint()`
3. `seed()`

In [ ]:
#Generating 5 random numbers from 0-1

# when we are dealing with random numbers, we have to use a SUBLIBRARY/SUBPACKAGE in numpy --> (np.random)

# library                   - main chapter - Chapter 1          -  (numpy)
# sublibrary                - subchapter - Chapter 1.1          -  (random)
# method/commands           - topic    - Chapter 1.1.1 (hello)  -     (rand)

arr1 = np.random.rand(5)

print(arr1)

[0.78611632 0.87489889 0.76837886 0.2809133  0.64733919]


In [ ]:
# create a matrix of rand()

# matrix (mathematical term) - rows & columns


arr2 = np.random.rand(4,2)

print(arr2)

[[0.73948017 0.09477617]
 [0.0577931  0.7347796 ]
 [0.26842528 0.50433414]
 [0.42516232 0.07024935]]


# 2. randint


In [ ]:
#np.random.randint(start value , stop value )

num1 = np.random.randint(0,100)

print(num1)

86


In [ ]:
# 3 inputs

# 1st input - start
# 2nd input - end (exclude end)
# 3rd input - how many items in the array?


arr3 = np.random.randint(50,100,20)

print(arr3)

[76 79 65 72 77 94 91 89 88 60 68 56 82 86 61 99 85 79 93 79]


# 3. seed

In [ ]:
np.random.rand(4)

array([0.32784894, 0.78027808, 0.77731612, 0.13481887])

In [ ]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

## 1.3 Shape

Concept of changing/reshaping dimensions

In [ ]:
arr1 = np.arange(25)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
print(arr1.shape)

# Shape (25,) —> is a 1D array with 25 elements —> array([1, 2, 3,....])


(25,)


In [ ]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr1.reshape(4,3)

ValueError: cannot reshape array of size 25 into shape (4,3)

In [ ]:
#The shape of your matrix must be based on the number of data you created
#25
#1*25-> .reshape(1,25)
#25*1 -> .reshape(25,1)
#5*5 -> .reshape(5,5)

#.reshape(number of rows,number of columns)

## 1.4 Dtype

In [ ]:
arr1 = np.array([11,22,33,44])

print(type(arr1)) #  data type --> numpy array
print("-"*10)
print(arr1.dtype) # dtype --> int (specifically refers to the data type of the elements stored in the array)

<class 'numpy.ndarray'>
----------
int64


In [ ]:
arr1 = np.array([2.2,3.3,4.4,5.5])

print(type(arr1)) #  data type --> numpy array
print('---')
print(arr1.dtype) # dtype --> float (specifically refers to the data type of the elements stored in the array)

<class 'numpy.ndarray'>
---
float64


In [ ]:
arr1 = np.array(["jun","jun2","jun3"])

print(type(arr1)) #  data type --> numpy array
print('---')
print(arr1.dtype) # dtype --> <U4 (string) (specifically refers to the data type of the elements stored in the array)
# <U4 means strings under 4 characters long

# unicode
# encoding  (changing from characters to binaries)
# a --> 010

<class 'numpy.ndarray'>
---
<U4
